name: saarhti
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  get: ^4.6.6
  intl: ^0.19.0
  get_storage: ^2.1.1
  logger: ^2.4.0
  permission_handler: ^11.1.0
  iconsax: ^0.0.8
  table_calendar: ^3.1.2
  # firebase_auth: ^4.16.0
  smooth_page_indicator: ^1.2.0+3
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.9.0
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.7.1
  # geolocator: ^13.0.1
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/logos
    - assets/splashScreen/
